// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUa09HYrW9CMRxpBoHtGfdG0BUyslueAY',
    appId: '1:148764355912:web:44039fb0a38ac4978f577d',
    messagingSenderId: '148764355912',
    projectId: 'fbb01-3189c',
    authDomain: 'fbb01-3189c.firebaseapp.com',
    databaseURL: 'https://fbb01-3189c-default-rtdb.firebaseio.com',
    storageBucket: 'fbb01-3189c.appspot.com',
    measurementId: 'G-57T15ZTLW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzsTbFjsZaNw4tsI6svsXXDmbrtEpDpZg',
    appId: '1:148764355912:android:d161cd455fabc3318f577d',
    messagingSenderId: '148764355912',
    projectId: 'fbb01-3189c',
    databaseURL: 'https://fbb01-3189c-default-rtdb.firebaseio.com',
    storageBucket: 'fbb01-3189c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrwkhZrlIozSX9aY_Z14QzSz8ic4LuakY',
    appId: '1:148764355912:ios:1f2dc1a9ac3868ac8f577d',
    messagingSenderId: '148764355912',
    projectId: 'fbb01-3189c',
    databaseURL: 'https://fbb01-3189c-default-rtdb.firebaseio.com',
    storageBucket: 'fbb01-3189c.appspot.com',
    iosBundleId: 'com.example.fypAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrwkhZrlIozSX9aY_Z14QzSz8ic4LuakY',
    appId: '1:148764355912:ios:1f2dc1a9ac3868ac8f577d',
    messagingSenderId: '148764355912',
    projectId: 'fbb01-3189c',
    databaseURL: 'https://fbb01-3189c-default-rtdb.firebaseio.com',
    storageBucket: 'fbb01-3189c.appspot.com',
    iosBundleId: 'com.example.fypAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUa09HYrW9CMRxpBoHtGfdG0BUyslueAY',
    appId: '1:148764355912:web:e47fbbff910044ee8f577d',
    messagingSenderId: '148764355912',
    projectId: 'fbb01-3189c',
    authDomain: 'fbb01-3189c.firebaseapp.com',
    databaseURL: 'https://fbb01-3189c-default-rtdb.firebaseio.com',
    storageBucket: 'fbb01-3189c.appspot.com',
    measurementId: 'G-91YFDWPBHK',
  );
}
